Fix 'bindgen' version error
Error:

    cargo test
    Updating crates.io index
    error: failed to select a version for the requirement `bindgen = "^0.54.1"`
    candidate versions found which didn't match: 0.55.1, 0.55.0, 0.54.0, ...
    location searched: crates.io index
    required by package `tfmicro v0.1.0 (/Users/tallamjr/github/EDGE22/forks/tfmicro)`

	modified:   Cargo.toml